### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by shawn1thompson** [mehmetakiftutuncu/Muezzin#10]
Customizing prayer times would be a good feature to implement if possible. Specifically, being able to use an angle for Fajr and Isha and differentiating between the Hanafi and other Asr times. 

Also, options to use different sources would be good as well. Specifically, I would like to see something using sun times as in [this](https://forrestguice.github.io/SuntimesWidget/)  project.

**Comment by makiftutuncu** [comment]
Unfortunately, I'm not actively maintaining this application anymore. One of the features I had in my mind was to add the ability to set offsets for individual prayer times so that a user can make corrections if needed. This would probably solve your issue. I'll keep this in mind if I ever work on this app in the future. Thanks for the feedback.

**Comment by shawn1thompson** [comment]
Unfortunate...I would really like an open source prayer times app, especially since somewhat recent revelations concerning some of the closed source apps.
